### ISSUE TITLE
No C++ API for image IO

### ISSUE THREAD

**Issue by siebenkopf** [bioidiap/bob.io.image#1]
I would like to read some images inside C++. Unfortunately, it seems that there is no C++ API defined for loading and writing images, but only Python bindings.

Is there any plan to provide an image IO API for C++ as well?

**Comment by anjos** [comment]
No current plans. You're welcome to extend it and submit a patch or merge it directly.

**Comment by siebenkopf** [comment]
I have started writing and exporting IO functions in C++. I have currently implemented the JPEG IO, by providing functions ``read_jpeg`` and ``write_jpeg``:
https://github.com/bioidiap/bob.io.image/blob/C%2B%2Binterface/bob/io/image/include/bob.io.image/io.h#L37
Both can have either gray or color images, depending on the ``<N>`` template parameter. I could also provide ``read_color_jpeg``, ``write_color_jpeg`` and ``read_gray_jpeg``, ``read_color_jpeg``. Which of the two versions do you prefer?

To be specific about the current (templated) version: I have instantiated both functions for both ``N=2`` and ``N=3``:
https://github.com/bioidiap/bob.io.image/blob/C%2B%2Binterface/bob/io/image/jpeg.cpp#L426
Using a different ``N`` will compile fine, but will give linker errors (undefined symbols).
I think this is OK, as long as it is documented. What do you think?

**Comment by anjos** [comment]
What you provided sounds OK already.

For moving the error from the linking stage to the compiling stage, you may use BOOST_STATIC_ASSERT: http://www.boost.org/doc/libs/1_43_0/doc/html/boost_staticassert.html

**Comment by siebenkopf** [comment]
In fact, I have changed my mind, and I will provide the full JPEGFile class in the header:
https://github.com/bioidiap/bob.io.image/blob/C%2B%2Binterface/bob/io/image/include/bob.io.image/jpeg.h
With that, we won't have the problem, as I can provide the template implementation in the header file. Also, other functions of the class can be used as well, such as the ``cast`` function from the base class:
https://github.com/bioidiap/bob.io.base/blob/master/bob/io/base/include/bob.io.base/File.h#L103

I will go on and implement similar structure for the other image types, too.

**Comment by tiagofrepereira2012** [comment]
Thanks @siebenkopf 
As said in the google groups, the example package using the API is on gitlab-ci
