### ISSUE TITLE
Please replace netpbm with another library

### ISSUE THREAD

**Issue by 183amir** [bioidiap/bob.io.image#5]
Netpbm is old and it is very hard to package. It has [no clear license](https://fedoraproject.org/wiki/LicenseAuditRecords) and nobody uses it anyway.

**Comment by 183amir** [comment]
Also, we are having a lengthy discussion [here](https://github.com/conda-forge/staged-recipes/pull/237) about packaging `netpbm` for `conda`.

**Comment by jakirkham** [comment]
Is there an option for a user to disable building with netpbm? I think this would be very useful for people uninterested in this functionality and running into various difficulties trying to get it to work.

**Comment by anjos** [comment]
I'm not sure how you devised nobody uses it. Some of our databases provide data in PGM format. For example, AT&T (the old ORL face database). Is there another library that implements this we could replace netpbm with?

**Comment by jakirkham** [comment]
Personally, not claiming that it is not used. However, I will attest to the fact that this is non-trivial to package and it would be nice for users that don't need this to opt out.

**Comment by anjos** [comment]
A simple way to do this would be to move the netpbm support out of this package into a separate package - say `bob.io.netpbm`.

**Comment by anjos** [comment]
There will likely be consequences to some of our software that reads data from older databases. To be throughly tested with our nightly builds.

**Comment by jakirkham** [comment]
Will that go cleanly? There seem to be [a few references]( https://github.com/bioidiap/bob.io.image/search?utf8=%E2%9C%93&q=netpbm ) outside of `bob.io.netpbm` that make use of this functionality.

**Comment by 183amir** [comment]
There is no package called `bob.io.netpbm` as of yet. `netpbm` is used in `bob.io.image`.
I think the best way would be to use an alternative to `netpbm`.

**Comment by anjos** [comment]
That would be also possible, if you can find a relatively stable solution. In the past, we used to link against ImageMagick and get everything out of it. Unfortunately, that library has a pretty unstable API so, we had to keep modifying it every few months. In the end, we decided to drop that in favour of using the individual image libraries (jpeg, libgif, libpng, netpbm, ...).

**Comment by 183amir** [comment]
Maybe imagemagic is stable enough now?

**Comment by anjos** [comment]
Humm... Difficult to tell what is best. I haven't followed that project for a while. I'd tend to split the packages and not do anything else. I think that is the most conservative and worry free solution.

If you decide to go the ImageMagick way, please implement that in a new package: `bob.io.imagemagick` and propose that as an alternative drop-in replacement to `bob.io.image` and let's see what sticks.

**Comment by jakirkham** [comment]
Personally, I think the simplest way forward here is adding a macro (e.g. `WITHOUT_NETPBM`) that when set blocks compilation of `bob.io.netpbm`. On the Python side, skips should be added for any tests. IMHO this will solve the OP's current issue and will be quite simple to implement.

**Comment by 183amir** [comment]
I guess dropping `netpbm` would not be that easy since a lot of other bob packages use that old AT&T database to run their tests; like `bob.bio.face`. Am I right @anjos?

**Comment by anjos** [comment]
Yes - you're right.

**Comment by jakirkham** [comment]
Alright, I will leave it up to you guys to figure out the best way forward here. Just noting that packaging netpbm is not feeling like the easiest one. ImageMagick would be way more straightforward.

**Comment by 183amir** [comment]
Well, I had a working packaging script untill you insisted that it was not good enough :D

**Comment by siebenkopf** [comment]
How difficult is it to have a custom implementation of loading PGM? As far as I know, this format is uncompressed and, hence, easy to read. 

What about merging the idea of @jakirkham by using netpbm as long as it is provided by the system, and our custom solution (maybe in read only mode), when not?

**Comment by jakirkham** [comment]
Yeah, sorry, I think I am a bit confused.

So, I understand that you want to keep netpbm support for testing. However, I am not understanding why an end user must keep netpbm support. It seems the OP has no real need for it. So, I don't understand why we must shoulder the burden of maintaining it if it won't be actively used (other than being a require dependency). It seems if the dependency is optional it would still be possible for you to build this to do the needed testing, but would free us from needing to build something we don't want to use.

Why again can netpbm not be made optional?

**Comment by anjos** [comment]
If we make this optional and netpbm is not available, then our unit tests will fail on the target machine. Moving the unit tests (we're taking about about a few hundred) to use other material that does not require netpbm is possible, but will be a somewhat larger task. I guess we're just trying to estimate what will be the smallest possible amount of work we can do to satisfy the conda packaging issue w.r.t. our own build infrastructure, tests and requirements.

**Comment by siebenkopf** [comment]
@jakirkham: I think we do use the package, as @anjos pointed out in the ORL database, which serves for unit testing and in other examples: https://github.com/bioidiap/bob.example.faceverify

However, I see that there might be an issue with the ``netpbm`` library on some systems. I also know that people are no big fans of custom implementations, as the more we implement the more we need to maintain. However, when having a look into the specification, there is a very simple way of reading images from the ORL database, which is (in Python):

```
import numpy
from matplotlib import pyplot
with open("1.pgm") as f:
  f.readline() # file header, should contain "P5\n"
  width, height = [int(s) for s in f.readline().strip().split()]  # read width and height in text mode
  f.readline() # third line in file; should contain "255\n"
  image = numpy.fromfile(f, numpy.uint8)
  image.shape = (height,width)
  pyplot.imshow(image, "gray")
```

(this code is tested and works with an image ``1.pgm`` from the ORL database)

We can implement it in Python (as it is) or in C++ (in case we can register extensions only in C++: https://github.com/bioidiap/bob.io.image/blob/master/bob/io/image/main.cpp#L89).
I am not sure if we need to support more types of pgm (see first line of file, which contains the format specification). We might just raise a ``NotImplementedError`` for those cases.

**Comment by jakirkham** [comment]
Given the responses above, I'd like to clarify another point that I am a bit unclear on. Was the initial plan to use the `netpbm` package in development with the `bob` project? In other words, would several people have been dependent on this package from conda-forge and have used it regularly for active development?

> Moving the unit tests (we're taking about about a few hundred) to use other material that does not require netpbm is possible, but will be a somewhat larger task.

Ah, I see. I was thinking the scope was a bit smaller. Certainly this is worth some thought.

> However, when having a look into the specification, there is a very simple way of reading images from the ORL database, which is (in Python)

Yeah, the spec for the format seems quite simple, which is why I am a bit perplexed at how complex netpbm (and packaging thereof) is. Though I am hardly an expert on it.

> We can implement it in Python (as it is) or in C++ (in case we can register extensions only in C++...)

If it needs to go into C/C++, NumPy's C-API (and Python's C-API for that matter) are quite straightforward so may end up being only slightly longer than the pure Python code to do this.

**Comment by siebenkopf** [comment]
``netpbm`` includes some more tricks to store the images, e.g., compression with run length encoding (RLE) or compression with 4-bit pixels, so that's probably why the library is larger. However, for our purpose (ORL) we need only the code that I pointed out above.

In C++, I don't think that we need the NumPy API to do the IO, a simple ``fread()`` (after reading the first three header lines) should do the trick.

**Comment by 183amir** [comment]
Netpbm is a software collection rather than one. There are so many
different codes for different purposes there.

**Comment by jakirkham** [comment]
> `netpbm` includes some more tricks to store the images, e.g., compression with run length encoding (RLE) or compression with 4-bit pixels, so that's probably why the library is larger. However, for our purpose (ORL) we need only the code that I pointed out above.

I see. Thanks for clarifying.

> In C++, I don't think that we need the NumPy API to do the IO, a simple fread() (after reading the first three header lines) should do the trick.

Sure vanilla C/C++ will probably do just as well. All depends on your style.
